# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QPlainTextEdit, QProgressBar, QPushButton, QSizePolicy,
    QWidget)
import rc_imagepatcherui

class Ui_ImagePatcherUI(object):
    def setupUi(self, ImagePatcherUI):
        if not ImagePatcherUI.objectName():
            ImagePatcherUI.setObjectName(u"ImagePatcherUI")
        ImagePatcherUI.resize(600, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImagePatcherUI.sizePolicy().hasHeightForWidth())
        ImagePatcherUI.setSizePolicy(sizePolicy)
        ImagePatcherUI.setMinimumSize(QSize(600, 600))
        ImagePatcherUI.setMaximumSize(QSize(600, 600))
        icon = QIcon()
        icon.addFile(u":/images/images/imagepatcherui.ico", QSize(), QIcon.Normal, QIcon.Off)
        ImagePatcherUI.setWindowIcon(icon)
        ImagePatcherUI.setAutoFillBackground(False)
        self.sourceLineEdit = QLineEdit(ImagePatcherUI)
        self.sourceLineEdit.setObjectName(u"sourceLineEdit")
        self.sourceLineEdit.setGeometry(QRect(20, 120, 430, 32))
        self.outputLineEdit = QLineEdit(ImagePatcherUI)
        self.outputLineEdit.setObjectName(u"outputLineEdit")
        self.outputLineEdit.setGeometry(QRect(20, 200, 430, 32))
        self.lowResOutputLineEdit = QLineEdit(ImagePatcherUI)
        self.lowResOutputLineEdit.setObjectName(u"lowResOutputLineEdit")
        self.lowResOutputLineEdit.setGeometry(QRect(20, 280, 430, 32))
        self.browseSourceButton = QPushButton(ImagePatcherUI)
        self.browseSourceButton.setObjectName(u"browseSourceButton")
        self.browseSourceButton.setGeometry(QRect(460, 120, 121, 32))
        self.browseOutputButton = QPushButton(ImagePatcherUI)
        self.browseOutputButton.setObjectName(u"browseOutputButton")
        self.browseOutputButton.setGeometry(QRect(460, 200, 121, 32))
        self.browseLowResOutputButton = QPushButton(ImagePatcherUI)
        self.browseLowResOutputButton.setObjectName(u"browseLowResOutputButton")
        self.browseLowResOutputButton.setGeometry(QRect(460, 280, 121, 32))
        self.labelSourceFolder = QLabel(ImagePatcherUI)
        self.labelSourceFolder.setObjectName(u"labelSourceFolder")
        self.labelSourceFolder.setGeometry(QRect(20, 90, 300, 32))
        font = QFont()
        font.setPointSize(16)
        self.labelSourceFolder.setFont(font)
        self.labelSourceFolder.setTextInteractionFlags(Qt.NoTextInteraction)
        self.labelOutputFolder = QLabel(ImagePatcherUI)
        self.labelOutputFolder.setObjectName(u"labelOutputFolder")
        self.labelOutputFolder.setGeometry(QRect(20, 170, 300, 32))
        self.labelOutputFolder.setFont(font)
        self.labelOutputFolder.setTextInteractionFlags(Qt.NoTextInteraction)
        self.labelOutputLowResFolder = QLabel(ImagePatcherUI)
        self.labelOutputLowResFolder.setObjectName(u"labelOutputLowResFolder")
        self.labelOutputLowResFolder.setGeometry(QRect(20, 250, 300, 32))
        self.labelOutputLowResFolder.setFont(font)
        self.labelOutputLowResFolder.setTextInteractionFlags(Qt.NoTextInteraction)
        self.labelPatchSize = QLabel(ImagePatcherUI)
        self.labelPatchSize.setObjectName(u"labelPatchSize")
        self.labelPatchSize.setGeometry(QRect(20, 340, 300, 32))
        self.labelPatchSize.setFont(font)
        self.labelPatchSize.setTextInteractionFlags(Qt.NoTextInteraction)
        self.labelLowResScale = QLabel(ImagePatcherUI)
        self.labelLowResScale.setObjectName(u"labelLowResScale")
        self.labelLowResScale.setGeometry(QRect(20, 400, 300, 32))
        self.labelLowResScale.setFont(font)
        self.labelLowResScale.setTextInteractionFlags(Qt.NoTextInteraction)
        self.comboBoxScale = QComboBox(ImagePatcherUI)
        self.comboBoxScale.addItem("")
        self.comboBoxScale.addItem("")
        self.comboBoxScale.addItem("")
        self.comboBoxScale.addItem("")
        self.comboBoxScale.setObjectName(u"comboBoxScale")
        self.comboBoxScale.setGeometry(QRect(460, 400, 121, 32))
        self.patchSizeText = QPlainTextEdit(ImagePatcherUI)
        self.patchSizeText.setObjectName(u"patchSizeText")
        self.patchSizeText.setGeometry(QRect(460, 340, 121, 32))
        self.patchSizeText.setOverwriteMode(False)
        self.processButton = QPushButton(ImagePatcherUI)
        self.processButton.setObjectName(u"processButton")
        self.processButton.setGeometry(QRect(20, 457, 561, 81))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        self.processButton.setFont(font1)
        self.labelTitle = QLabel(ImagePatcherUI)
        self.labelTitle.setObjectName(u"labelTitle")
        self.labelTitle.setGeometry(QRect(9, 9, 291, 41))
        font2 = QFont()
        font2.setPointSize(22)
        font2.setBold(False)
        font2.setItalic(True)
        font2.setKerning(False)
        self.labelTitle.setFont(font2)
        self.progressBar = QProgressBar(ImagePatcherUI)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(0, 568, 600, 32))
        self.progressBar.setValue(0)
        self.logoButton = QPushButton(ImagePatcherUI)
        self.logoButton.setObjectName(u"logoButton")
        self.logoButton.setGeometry(QRect(380, 8, 210, 50))
        self.logoButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/images/images/JMDigital.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logoButton.setIcon(icon1)
        self.logoButton.setIconSize(QSize(200, 46))
        self.logoButton.setFlat(True)
        self.progressLabel = QLabel(ImagePatcherUI)
        self.progressLabel.setObjectName(u"progressLabel")
        self.progressLabel.setGeometry(QRect(10, 570, 581, 26))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setItalic(True)
        font3.setKerning(False)
        self.progressLabel.setFont(font3)

        self.retranslateUi(ImagePatcherUI)

        self.comboBoxScale.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(ImagePatcherUI)
    # setupUi

    def retranslateUi(self, ImagePatcherUI):
        ImagePatcherUI.setWindowTitle(QCoreApplication.translate("ImagePatcherUI", u"Image Patcher UI by JMDigital", None))
#if QT_CONFIG(tooltip)
        self.sourceLineEdit.setToolTip(QCoreApplication.translate("ImagePatcherUI", u"<html><head/><body><p>Browse for a folder that contains your highest resolution images. Note: Images MUST be larger than your desired Patch Size</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sourceLineEdit.setPlaceholderText(QCoreApplication.translate("ImagePatcherUI", u"This is your input folder containing all the images you want to process", None))
        self.outputLineEdit.setPlaceholderText(QCoreApplication.translate("ImagePatcherUI", u"This is your output folder containing the full size patched images", None))
        self.lowResOutputLineEdit.setPlaceholderText(QCoreApplication.translate("ImagePatcherUI", u"This is your output folder containing the scaled Low-Res size patched images", None))
        self.browseSourceButton.setText(QCoreApplication.translate("ImagePatcherUI", u"Browse", None))
        self.browseOutputButton.setText(QCoreApplication.translate("ImagePatcherUI", u"Browse", None))
        self.browseLowResOutputButton.setText(QCoreApplication.translate("ImagePatcherUI", u"Browse", None))
        self.labelSourceFolder.setText(QCoreApplication.translate("ImagePatcherUI", u"Source Folder:", None))
        self.labelOutputFolder.setText(QCoreApplication.translate("ImagePatcherUI", u"Output Folder:", None))
        self.labelOutputLowResFolder.setText(QCoreApplication.translate("ImagePatcherUI", u"Output Low-Res Folder:", None))
        self.labelPatchSize.setText(QCoreApplication.translate("ImagePatcherUI", u"Patch Size:", None))
        self.labelLowResScale.setText(QCoreApplication.translate("ImagePatcherUI", u"Low-Res Scale:", None))
        self.comboBoxScale.setItemText(0, QCoreApplication.translate("ImagePatcherUI", u"2x", None))
        self.comboBoxScale.setItemText(1, QCoreApplication.translate("ImagePatcherUI", u"4x", None))
        self.comboBoxScale.setItemText(2, QCoreApplication.translate("ImagePatcherUI", u"6x", None))
        self.comboBoxScale.setItemText(3, QCoreApplication.translate("ImagePatcherUI", u"8x", None))

#if QT_CONFIG(statustip)
        self.patchSizeText.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.patchSizeText.setPlainText("")
        self.patchSizeText.setPlaceholderText(QCoreApplication.translate("ImagePatcherUI", u"e.g 512 (without px)", None))
        self.processButton.setText(QCoreApplication.translate("ImagePatcherUI", u"Process", None))
        self.labelTitle.setText(QCoreApplication.translate("ImagePatcherUI", u"Image Patcher UI", None))
        self.logoButton.setText("")
        self.progressLabel.setText("")
    # retranslateUi

